### PR TITLE
Move default source cache path under /var/cache instead of /var/spool

### PR DESCRIPTION
**Pull request by fractalcat**
Don't merge yet, needs more testing.

### CODE REVIEW

**Comment by fractalcat** [comment]
Seems alright thus far, good to proceed with merge if the patch looks okay.

**Comment by afcowie** [comment]
Perhaps its a different issue, but the filenames within whichever directory also seemed a bit overblown. Am I just bikeshedding?

**Comment by fractalcat** [comment]
@afcowie how does that look?

**Comment by fractalcat** [comment]
This has been around for a while, gonna assume no-one objects to the changes herein. If anyone does, you have maybe ten more minutes to say so.

**Comment by fractalcat** [comment]
May as well test Hipchat integration while I'm here

**Pull request merged**
