### PR TITLE
Fix up cabal warnings

### PR DESCRIPTION
**Pull request by fractalcat**

### CODE REVIEW

**Comment by tranma** [comment]
why no O2?

**Comment by fractalcat** [comment]
Why do we need it? Do we have any data indicating that it's useful in this case?

**Comment by tranma** [comment]
just a good default. Most of the time O2 is the best. @christian-marie added it, maybe he knows what helped

**Comment by christian-marie** [comment]
Decoding loops used to be in it. I believe there was a speed-up on benchmarks? These assumptions may not hold any more.

**Comment by fractalcat** [comment]
Alright, it's back in.

**Comment by fractalcat** [comment]
Any further objections @tranma @christian-marie?

**Pull request merged**
